import{createMcpHandler}from"mcp-handler";import{z}from"zod";
export const runtime="nodejs";export const maxDuration=60;export const dynamic="force-dynamic";
const methods=new Set(["tasks/send","tasks/get","tasks/update","tasks/cancel"]),Json=z.record(z.string(),z.unknown());
function mutations(){return String(process.env.AKASHIC_MUTATIONS_ENABLED??"false").toLowerCase()==="true"}
function result(data,text="Akashic operation completed."){return{structuredContent:data,content:[{type:"text",text}]}}
function failure(e){const code=typeof e?.code==="string"?e.code:"akashic_error",message=e instanceof Error?e.message:String(e);return{isError:true,structuredContent:{ok:false,error:{code,message}},content:[{type:"text",text:`${code}: ${message}`}]} }
function runnerUrl(){const raw=(process.env.AKASHIC_RUNNER_URL??"").trim();if(!raw)throw Object.assign(new Error("AKASHIC_RUNNER_URL is not configured"),{code:"runner_not_configured"});const u=new URL(raw),local=["localhost","127.0.0.1","::1"].includes(u.hostname);if(!["http:","https:"].includes(u.protocol)||u.protocol!=="https:"&&!local)throw Object.assign(new Error("remote runner must use HTTPS"),{code:"invalid_runner_url"});u.pathname=u.pathname.replace(/\/+$/,"");u.search="";u.hash="";return u}
function requireMutation(){if(!mutations())throw Object.assign(new Error("mutating tools are disabled until authenticated explicitly"),{code:"mutations_disabled"})}
function sanitize(v){if(v===null||["string","number","boolean"].includes(typeof v))return v;if(Array.isArray(v))return v.slice(0,256).map(sanitize);if(typeof v==="object"){const o={};for(const[k,x]of Object.entries(v).slice(0,256)){if(!/token|secret|password|authorization|cookie/i.test(k))o[k]=sanitize(x)}return o}return String(v)}
async function rpc(method,params){if(!methods.has(method))throw Object.assign(new Error("unsupported runner method"),{code:"unsupported_method"});const base=runnerUrl(),url=new URL(`${base.pathname}/a2a`.replace(/\/{2,}/g,"/"),base),controller=new AbortController(),timer=setTimeout(()=>controller.abort(),30000),headers={"content-type":"application/json"};if(process.env.AKASHIC_RUNNER_TOKEN)headers.authorization=`Bearer ${process.env.AKASHIC_RUNNER_TOKEN}`;try{const r=await fetch(url,{method:"POST",headers,body:JSON.stringify({jsonrpc:"2.0",id:crypto.randomUUID(),method,params}),signal:controller.signal,redirect:"error",cache:"no-store"}),p=await r.json().catch(()=>({}));if(!r.ok||p.error)throw Object.assign(new Error(p?.error?.message||`runner HTTP ${r.status}`),{code:"runner_rpc_error"});return sanitize(p.result??p)}catch(e){if(e?.name==="AbortError")throw Object.assign(new Error("runner timeout"),{code:"runner_timeout"});throw e}finally{clearTimeout(timer)}}
const handler=createMcpHandler(server=>{
server.registerTool("akashic_status",{title:"Akashic status",description:"Use this when you need gateway configuration and, when configured, current runner health before dispatching work.",inputSchema:z.object({}),annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:false}},async()=>{try{let runner=null;if(process.env.AKASHIC_RUNNER_URL){const u=runnerUrl(),r=await fetch(new URL(`${u.pathname}/healthz`.replace(/\/{2,}/g,"/"),u),{cache:"no-store"});runner=sanitize(await r.json().catch(()=>({status:r.status})))}return result({ok:true,gateway:{platform:"vercel",version:"0.6.0",mutations_enabled:mutations()},runner},"Akashic status loaded.")}catch(e){return failure(e)}});
server.registerTool("akashic_deployment_plan",{title:"Akashic deployment plan",description:"Use this when you need the fixed responsibility split among Vercel, Cloudflare, Sites, GitHub, Drive, WASM, and execution runners.",inputSchema:z.object({}),annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:false}},async()=>result({gateway:"Vercel MCP",durable_kernel:"Cloudflare Durable Objects (next)",source:"GitHub commit-pinned snapshots",artifacts:"Google Drive",execution:"local/VM for subscription CLI; cloud sandbox for API-auth build/test",ui:"ChatGPT and optional Sites console",wasm:"deterministic Context Plane only"},"Deployment plan loaded."));
server.registerTool("akashic_submit_task",{title:"Submit Akashic task",description:"Use this when a bounded Task Capsule is ready. Returns immediately with SUBMITTED or idempotent replay.",inputSchema:z.object({task:Json}),annotations:{readOnlyHint:false,destructiveHint:false,idempotentHint:true,openWorldHint:true}},async({task})=>{try{requireMutation();return result(await rpc("tasks/send",{task}),"Task submitted.")}catch(e){return failure(e)}});
server.registerTool("akashic_get_task",{title:"Get Akashic task",description:"Use this to poll compact task state, including INPUT_REQUIRED and artifact references.",inputSchema:z.object({task_id:z.string().min(1).max(120),since_seq:z.number().int().min(0).optional(),wait_ms:z.number().int().min(0).max(30000).default(0)}),annotations:{readOnlyHint:true,destructiveHint:false,openWorldHint:false}},async({task_id,since_seq,wait_ms})=>{try{return result(await rpc("tasks/get",{id:task_id,...(since_seq===undefined?{}:{since_seq}),wait_ms,view:"compact"}),"Task state loaded.")}catch(e){return failure(e)}});
server.registerTool("akashic_apply_context_delta",{title:"Apply context delta",description:"Use this only for an INPUT_REQUIRED task with a schema-valid CAS-guarded ContextPacketDelta.",inputSchema:z.object({task_id:z.string().min(1).max(120),context_delta:Json}),annotations:{readOnlyHint:false,destructiveHint:false,idempotentHint:true,openWorldHint:false}},async({task_id,context_delta})=>{try{requireMutation();return result(await rpc("tasks/update",{id:task_id,context_delta}),"Context delta applied.")}catch(e){return failure(e)}});
server.registerTool("akashic_cancel_task",{title:"Cancel Akashic task",description:"Use this to interrupt and durably cancel a nonterminal task.",inputSchema:z.object({task_id:z.string().min(1).max(120)}),annotations:{readOnlyHint:false,destructiveHint:true,idempotentHint:true,openWorldHint:false}},async({task_id})=>{try{requireMutation();return result(await rpc("tasks/cancel",{id:task_id}),"Cancellation requested.")}catch(e){return failure(e)}})
});export{handler as GET,handler as POST};
